spring.application.name=SPRING-AI-PROJECT
server.port=8081


#openai properties
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4.1
spring.ai.openai.chat.options.temperature=0.2

#what model i am using?provide me the version